CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Roles" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Key" text NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Statuses" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Color" text NULL,
    "Discriminator" text NOT NULL,
    CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
);

CREATE TABLE "Teams" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Email" text NULL,
    "Password" text NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "RoleId" integer NOT NULL,
    "TeamId" integer NULL,
    "Discriminator" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Requests" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "Price" double precision NOT NULL,
    "DateDeadLine" timestamp without time zone NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "CustomerId" integer NOT NULL,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requests_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Contracts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "DateStart" timestamp without time zone NOT NULL,
    "DateDeadLine" timestamp without time zone NOT NULL,
    "DateEnd" timestamp without time zone NOT NULL,
    "RequestId" integer NOT NULL,
    "PlannerId" integer NOT NULL,
    CONSTRAINT "PK_Contracts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contracts_Users_PlannerId" FOREIGN KEY ("PlannerId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Contracts_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RequestStatusHistories" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StatusId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_RequestStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RequestStatusHistories_Requests_EntityId" FOREIGN KEY ("EntityId") REFERENCES "Requests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RequestStatusHistories_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContractStages" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "DateStart" timestamp without time zone NOT NULL,
    "DateDeadLine" timestamp without time zone NOT NULL,
    "DateEnd" timestamp without time zone NOT NULL,
    "ContractId" integer NOT NULL,
    CONSTRAINT "PK_ContractStages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractStages_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContractStatusHistories" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StatusId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ContractStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractStatusHistories_Contracts_EntityId" FOREIGN KEY ("EntityId") REFERENCES "Contracts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContractStatusHistories_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Projects" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "DateStart" timestamp without time zone NOT NULL,
    "ContractId" integer NOT NULL,
    "TeamId" integer NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Projects_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Projects_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProjectStages" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "ProjectId" integer NOT NULL,
    "ExecutorId" integer NULL,
    "ContractStageId" integer NOT NULL,
    CONSTRAINT "PK_ProjectStages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectStages_ContractStages_ContractStageId" FOREIGN KEY ("ContractStageId") REFERENCES "ContractStages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectStages_Users_ExecutorId" FOREIGN KEY ("ExecutorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProjectStages_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProjectStatusHistories" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StatusId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ProjectStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectStatusHistories_Projects_EntityId" FOREIGN KEY ("EntityId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectStatusHistories_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tasks" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    "DateStart" timestamp without time zone NOT NULL,
    "DateDeadLine" timestamp without time zone NOT NULL,
    "DateEnd" timestamp without time zone NOT NULL,
    "ExecutorId" integer NULL,
    "StageId" integer NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tasks_Users_ExecutorId" FOREIGN KEY ("ExecutorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tasks_ProjectStages_StageId" FOREIGN KEY ("StageId") REFERENCES "ProjectStages" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskStatusHistories" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "StatusId" integer NOT NULL,
    "EntityId" integer NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TaskStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskStatusHistories_Tasks_EntityId" FOREIGN KEY ("EntityId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskStatusHistories_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE
);

INSERT INTO "Roles" ("Id", "Key", "Name")
VALUES (4, 'tl', 'Тимлид');
INSERT INTO "Roles" ("Id", "Key", "Name")
VALUES (3, 'pl', 'Сотрудник отдела планирования');
INSERT INTO "Roles" ("Id", "Key", "Name")
VALUES (2, 'empl', 'Сотрудник');
INSERT INTO "Roles" ("Id", "Key", "Name")
VALUES (1, 'cust', 'Заказчик');

INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (10, NULL, 'ContractStatus', 'Завершен');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (6, '#36b37e', 'TaskStatus', 'Готово');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (1, NULL, 'RequestStatus', 'В обработке');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (5, '#0052cc', 'TaskStatus', 'В работе');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (3, NULL, 'RequestStatus', 'Отказано');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (14, '#d04437', 'ProjectStatus', 'Отклонен');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (2, '#0052cc', 'ProjectStatus', 'Активный проект');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (13, '#36b37e', 'ProjectStatus', 'Завершен');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (8, NULL, 'ContractStatus', 'Ожидание работ');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (11, NULL, 'ContractStatus', 'Отклонён');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (9, NULL, 'ContractStatus', 'В работе');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (7, NULL, 'RequestStatus', 'Завершен');
INSERT INTO "Statuses" ("Id", "Color", "Discriminator", "Name")
VALUES (4, '#dfe1e6', 'TaskStatus', 'К выполнению');

CREATE INDEX "IX_Contracts_PlannerId" ON "Contracts" ("PlannerId");

CREATE INDEX "IX_Contracts_RequestId" ON "Contracts" ("RequestId");

CREATE INDEX "IX_ContractStages_ContractId" ON "ContractStages" ("ContractId");

CREATE INDEX "IX_ContractStatusHistories_EntityId" ON "ContractStatusHistories" ("EntityId");

CREATE INDEX "IX_ContractStatusHistories_StatusId" ON "ContractStatusHistories" ("StatusId");

CREATE INDEX "IX_Projects_ContractId" ON "Projects" ("ContractId");

CREATE INDEX "IX_Projects_TeamId" ON "Projects" ("TeamId");

CREATE INDEX "IX_ProjectStages_ContractStageId" ON "ProjectStages" ("ContractStageId");

CREATE INDEX "IX_ProjectStages_ExecutorId" ON "ProjectStages" ("ExecutorId");

CREATE INDEX "IX_ProjectStages_ProjectId" ON "ProjectStages" ("ProjectId");

CREATE INDEX "IX_ProjectStatusHistories_EntityId" ON "ProjectStatusHistories" ("EntityId");

CREATE INDEX "IX_ProjectStatusHistories_StatusId" ON "ProjectStatusHistories" ("StatusId");

CREATE INDEX "IX_Requests_CustomerId" ON "Requests" ("CustomerId");

CREATE INDEX "IX_RequestStatusHistories_EntityId" ON "RequestStatusHistories" ("EntityId");

CREATE INDEX "IX_RequestStatusHistories_StatusId" ON "RequestStatusHistories" ("StatusId");

CREATE INDEX "IX_Tasks_ExecutorId" ON "Tasks" ("ExecutorId");

CREATE INDEX "IX_Tasks_StageId" ON "Tasks" ("StageId");

CREATE INDEX "IX_TaskStatusHistories_EntityId" ON "TaskStatusHistories" ("EntityId");

CREATE INDEX "IX_TaskStatusHistories_StatusId" ON "TaskStatusHistories" ("StatusId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

CREATE INDEX "IX_Users_TeamId" ON "Users" ("TeamId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201124154955_Initial', '3.1.9');

